name: coral
version: "0.1.0"
github: "luisholanda/coral"
license: MIT
author: "Luis Holanda <holandal@acm.org>"
maintainer: "Luis Holanda <holandal@acm.org>"

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml

dependencies:
  - text

default-extensions:
  - OverloadedStrings
  - UnicodeSyntax
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances

library:
  build-tools:
    - alex
    - happy
  dependencies:
    - base
    - containers
    - bytestring
    - utf8-string
    - prettyprinter
    - array
    - vector
    - mtl
    - lens
    - hashable
  source-dirs: library
  default-extensions:
    - DeriveDataTypeable
    - DeriveFunctor
    - BangPatterns
    - LambdaCase
    - NamedFieldPuns

executables:
  coral:
    source-dirs: executable
    main: Main.hs
    dependencies:
      - base
      - coral
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

benchmarks:
  coral-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - base
      - coral
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  coral-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
      - base
      - coral
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
